---
sign_in: 登录
sign_up: 会员注册
agent_panel: 代理小组
admin_panel: 联系小组
country: 国家
state_province: 州/省
city: 市
register: 注册
details: 详细信息
view_all: 查看全部
order_by: 顺序按
none: 无
terms_and_conditions: 条款和条件
reg_success_message: ，您的帐户注册成功。电子邮件发送到您的邮箱。请按照该电子邮件激活您的帐户。由于
limit: 限制
usage: 使用
recover: 恢复
oops: 找不到网页
share_this: 分享此
location_map: 位置地图
image_gallery: 图片廊
gallery: 画廊
summary: 摘要
overview: 概述
address: 地址
message: 信息
email_subject: 电子邮件主题
all: 的所有
contact_us: 联系我们
featured_video: 精选视频
embed_video_url: 嵌入式视频网址
email_tracker: 电子邮件跟踪器
bulk_email: 大量电子邮件
advanced_filters: 高级过滤器
result: 结果
payment_notification: 你会作出付款。电子邮件被发送到您的电子邮件。您可以从链接返回到这一步随时随地对邮件。
confirmation: 确认
tags: 标签
zip_code: 邮编
embed_preview: 嵌入预览
login: 登录
post_not_found: 后未找到
view_more: 查看更多
choose_a_package: 选择软件包
choose_feature_package: 选择一个功能包
no_package_found: 不包找到
days: 天
posts: 的帖子
change: 更改
subscribe: 订阅
image: 图片
view_on_map: 查看地图（自动填充纬度郎）
create: 创建
basic_info: 基本信息
send: 发送
all_email_to_users: 的所有电子邮件到用户
email_detail: 的电子邮件详细
change_package: 更改套餐
bank_transfer: 银行转账
contact_subject: 联系电子邮件
payment_finish_title: 付款完成
payment_renew_title: 付款完成
payment_finish_text: 付款完毕。正如我们从贝宝帐户将被激活，收到确认尽快
payment_renew_text: 付款完毕。由于我们收到的确认贝宝帐户将会被更新很快
payment_cancel_title: 付款取消
payment_cancel_text: 您的付款被取消
feature_payment_finish: 付款完毕。只要我们从贝宝收到确认信息，你的财产将被功能。
feature_payment_cancel: 您的付款被取消。
selected_package: 所选套餐
signup_with_social_account: 注册与社会帐号
password: 密码
confirm_password: 确认密码
all_posts: 的所有帖子
no_posts: 没有帖子
title: 标题
description: 描述
status: 状态
actions: 操作
action: 动作
type: 类型
type_something: 类型的东西
content: 的内容
featured_image: 特色图片[分钟300x226]
category: 汽车类别
all_categories: 所有的汽车类
edit_category: 编辑类
new_category: 新车类别
parent: 父
edit: 编辑
delete: 删除
name: 名称
save: 保存
no_parent: 无父
edit_email_template: 编辑电子邮件模板
select_template_file: 选择模板文件
subject: 主题
body: 车身
available_variables: 可用变量
select_language: 选择语言
select_language_file: 选择语言文件
edit_as_new: 编辑为新
language: 语言
add_another: 添加另一个
export_to_file: 导出到文件
import_from_file: 从文件导入
auto_translator: 自动翻译
from_lang: 从郎
target_lang_full_name: 目标郎全名
target_lang_short_name: 目标郎短名称
create_new_package: 创建新的套餐
price: 价格
ask_for_price: 问问价格
maximum_post_by_user: 最高职位由用户
expiration_time: 过期时间（天）
create_package: 创建包
edit_package: 编辑包
update_package: 更新包
add_packages: 添加包
all_packages: 所有包
no_packages: 没有软件包
options: 选项
all_pages: 所有页面
no_pages: 没有页面
manage_menu: 管理菜单
menu_title: 菜单标题
menu_alias: 菜单别名
show_in_menu: 显示在菜单
page_layout: 页面布局
content_from: 内容从
url: 网址
seo_options: 搜索引擎优化选项
meta_description: Meta描述
key_words: 关键词
crawl_after: 抓取后（天）
all_plugins: 所有的插件
no_plugins: 无插件
name_and_version: 名称和版本
change_password: 更改密码
current_password: 当前密码
new_password: 新密码
retype_password: 重新输入密码
password_reset_info_msg: 请首先设置新密码
profile_picture: 是否有头像
username: 用户名
email: 电子邮件
first_name: 名字
last_name: 姓
gender: 性别
phone: 电话
company_name: 公司名称
about_me: 关于我
facebook_account: 的Facebook帐户
twitter_account: Twitter帐户
linkedin_account: LinkedIn帐户
gp_account: 的Google+帐户
account_msg: ，请输入链接，不含http //
web_email_settings: 网页电子邮件设置
contact_email: 联系人电子邮件
webadmin_name: WebAdmin的名称
webadmin_email: 网站管理电子邮件
update: 更新
upload: 上传
site_settings: 网站设置
site_title: 网站标题
footer_text: 页脚文本
site_logo: 网站的LOGO
site_language: 网站语言
site_text_direction: 网站的文字方向
per_page: 分页每页
default_page_layout: 默认页面布局
tracking_code: 跟踪代码
smtp_email_settings: SMTP电子邮件设置
smtp_email: SMTP电子邮件
smtp_host: SMTP主机
smtp_port: SMTP端口
smtp_timeout: SMTP超时
smtp_user: SMTP用户
smtp_password: SMTP密码
generate_site_map: 生成网站地图
sitemap_info_msg: NB请选择您要包含在XML网站地图。成功后一代sitemap.xml的是root目录下保存。您也可以编辑该文件包括你自己的网址。
pages: 网页
blog_posts: 博客
articles: 文章
blog_post: 博客文章
blog: 博客文章
article: 文章
news: 新闻
view_xml: 查看XML
create_xml: 创建XML
manage_backups: 管理备份
create_sql_backup: 创建SQL备份
create_image_backup: 创建映像备份
restore: 还原
download: 下载
dashboard: 仪表板
overview_stats_more: 概述，统计和更多
visit_site: 访问网站
logout: 登出
themes: 的主题
locations: 位置
paypal_settings: 贝宝设置
payment_history: 的付款历史
profile: 资料
packages: 包
widgets: 窗口部件
all_widgets: 的所有小工具
widget_positions: 窗口小部件的位置
blog_news_article: 博客/新闻/条
new_post: 新帖子
pages_and_menu: 页和菜单
new_page: 新建页面
menu: 菜单
system: 系统
manage_languages: 管理语言
auto_translate: 自动翻译
edit_email_text: 编辑电子邮件文本
admin_settings: 的Web管理员设置
sitemap: 网站地图
activate: 激活
active_theme: 活动的主题
available_themes: 可用主题
all_users: 所有用户
create_user: 创建用户
export_user_email: 导出用户的电子邮件（的.csv）
profile_info: 资料信息
ban_forever: 潘基永远
edit_page: 编辑页面
create_widget: 创建窗口小部件
widget_name: 窗口小部件名称
activate_deactivate: 激活/禁用
show: 显示
available_widgets: 可用的widget
active_widgets: 活动控件
delete_warning: 是否确定要删除
yes: “是”
no: “否”
product_name: 的内容
fa_icon: FA图标类
post_ad: 新增汽车
post_ad_subtitle: 把你的车的信息
signin: 登入
signup: 注册
signup_title: 创建您的帐户
not_found: 未找到
purpose: 目的
purpose_buy: 买入
purpose_sell: 卖出
select_category: 选择类别
contact_for_price: 价格联系
address_info: 地址信息
general_info: 基本信息
upload_later_msg: ，您将能够创建后后上传相册和视频网址
user_panel: 的用户面板
put_as_comma_seperated: 投入为（，）逗号sperated
added: 新增
location: 位置
views: 视图
package_type: 类型
post_package: 邮政包裹
featured_package: 精选包装
both_package: 后和特色
select_package: 选择包
package_created: 创建包
package_updated: 包更新
slider: 滑块
add_new: 添加新的
new_slide: 新的幻灯片
update_slide: 更新幻灯片
save_order: 保存以便
slider_sort_instruction: 您可以拖放到表行进行排序。排序保存订单后
search: 的搜索
results: 结果
location_on_map: 在地图上的位置
contact_mode: ，联系方式
reset: 复位
contact: 联系
default_site_view: 默认现场查看
type_your_message: 此处键入您的短信..
mail_sent: 邮寄
search_classifieds: 搜索汽车
advanced_search: 高级搜索
narrow_down_your_search: 缩小搜索
home: 首页
print: 打印
remember_me: 记住
forgot_password: 忘记密码
login_failed: 登录失败
login_to_your_account: 登录到您的帐户
register_your_account: 注册帐户
male: 男性
female: 女性
no_location_found: 没有位置找到
state: 状态
ad_creation_error: 的广告错误创建！请检查。
users: 用户
show_admin_user: 显示管理员用户
send_email_to_owner: 将电子邮件发送到车主
categories: 分类
top_posts: 置顶帖子
show_state_province: 显示国省
package_settings: 包设置
default_site_settings: 默认站点设置
webadmin_settings: 网站管理设置
banner_settings: 横幅设置
max_price_for_search: 最高出价的搜索
search_filters: 搜索过滤器
posts_per_page: 帖子每页
recent_posts: 最近的汽车
featured_posts: 精选文章
top_locations: 热门地区
top_users: 顶级用户
approve: 批准
make_featured: 制作专题
remove_featured: 删除功能
renew_featured: 续订功能的
renew_package: 续订包
no_renew_post_id: 无效的更新文章ID
approve_payment: 批准支付
transaction: 交易
transaction_id: 的交易ID
post_id: 文章ID
amount: 金额
request_date: 申请日期
expiration_date: 到期日
transaction_deleted: 的交易中删除
payment_approved: 已批准的付款
logged_in_as: 登录身份
posted_on: 发布在
confirm_email_send: 确认电子邮件send.Please遵循电子邮件的指示。
email_confirmed: 电子邮件确认。您可以立即登录
email_confirmed_failed: 电子邮件确认失败
password_change_success: 成功更改口令
email_sent_inbox: 电子邮件是发送到您的inbox.Check该电子邮件。
password_recovery_link_invalid: 密码恢复链接无效
user_updated: 用户更新
user_deleted: 用户删除
user_banned: 用户禁止
user_unbanned: 用户解除封锁
user_confirmed: 确认用户
post_deleted: 帖子删除
post_updated: 帖子更新
post_created: 后创建
post_featured: 邮政特色的
data_inserted: 数据插入
data_updated: 数据更新
feature_renewed: 功能续期
post_feature_removed: 后功能删除的
post_approved: 帖子批准
invalid_post: 无效邮政
email_sent: 邮件发送
settings_updated: 设置更新
package_removed: 包装中取出
page_updated: 页更新
page_created: 页创建的
page_deleted: 网页上删除了
menu_updated: 菜单更新
site_map_generation_success: 成功生成网站地图。
select_option: 请选择上或更多选择选项。
image_backup_created: 映像备份创建
language_translated: 语言翻译
unable_to_write_file: 无法写入文件
backup_deleted: 备份删除
database_restored: 还原数据库的
theme_activated: 主题激活
user_created: 用户创建的
widget_position_updated: 窗口小部件的位置更新
widget_created: 控件创建
widget_data_updated: 控件数据更新
unable_to_write_widget: 无法写入小部件
post_created_and_published: 后创建和发布
post_created_approval: 后创建，等待管理员批准
post_package_renewed: 邮政包裹重新
payment_finish: 付款完成
payment_cancelled: 取消支付
admin_change_pass_help: 留空白，如果没有变化需要
go_to_paypal: 转到贝宝
login_with_google: 登录与谷歌
login_with_facebook: 登录与Facebook
load_more_recent_posts: 加载更多最近的汽车
load_more_featured_posts: 装载更多精选汽车
register_for_new_account: 注册新帐号
site_map: 网站地图
show_site_map: 显示网站地图
service: 服务
features: 功能
about: 关于
view_posts: 搜索帖子
see_full_documentation: 查看完整的文档
select_city: 选择城市
parallax_slider: 视差滑块
all_slides: 所有的幻灯片
no_slide: 没有一张
slide_order: 幻灯片为了
edit_profile: 修改个人资料
post_price_settings: 后价格设置
enable_post_pricing: 启用后定价
enable_paypal_transfer: 启用贝宝
enable_bank_transfer: 启用银行转账
bank_transfer_instruction_for_posts: 银行转账指令
featured_price_settings: 精选的价格设定
enable_featured_pricing: 启用功能的定价
enable_featured_paypal: 使贝宝
enable_featured_bank_transfer: 启用银行转帐
bank_transfer_instruction_for_featured_posts: 银行转帐指令
bank_currency_settings: 银行货币设置
bank_currency: 银行外汇
use_same_as_paypal_currency: 使用相同的贝宝货币
admin: 管理员
re_password: 重新输入密码
explain_widget_position: 解释部件位置
post: 张贴
post_renew: 后续订
feature:功能
feature_renew: 特性续订
payment_for: 付款
select_country: 选择国家
select_one: 选择一个
video_url: 介绍用户网址
confirm_payment:确认付款
package_title: 包标题
number_of_featured_days: 的天数被推荐的
no_of_days: 无天的
any_city: 任何城市
any_category: 的任何类别
product_admin_panel: Carbiz管理员
username_or_email: 用户名或电子邮件
car_detail: 租车细节
posts_by: 帖子
featured: 精选
edit_user: 编辑用户
the_field_is_required: 的％的能量场是必需的。
valid_email: ％s文本框中必须包含一个有效的电子邮件地址。
min_length: 这％s字段必须至少％s的长度字符。
numeric: ％s文本框中只能包含数字。
matches: ％s文本框中不匹配％的能量场。
greater_than: ％s文本框中必须包含一个数字大于％s。
agree_terms: 我已阅读％的条款及细则％s的
must_accept_terms: 您必须接受条款和条件
dont_have_permission: ，您没有权限访问此页面
email_already_in_use: 已经电子邮件中使用
username_already_in_use: 用户名已在使用
current_password_not_matched: 当前密码不匹配
email_or_password_not_mathed: 的电子邮件或密码不匹配
email_not_matched: 的电子邮件不匹配
account_not_confirmed: 的帐户没有确认
all_locations: 所有地点
add_country: 添加国家
add_state: 添加状态
add_city: 添加城市
no_locations: 没有位置
banner_type: 横幅式
bg_image: 背景图片
unique_alias: ％s文本框中必须是唯一的
error_occurred: 时发生错误。请检查下面的字段
user_profile: 用户资料
user_email: 用户电子邮件
target_lang_name: 目标语言
no_emails: 没有电子邮件
to: 要
classified_settings: 分类设置
publish_posts_directly: 发布帖子直接
system_currency: 系统货币
enable_signup: 启用注册
if_package_expired: 如果包过期
do_not_hide: 不隐藏，
hide: 隐藏
show_price_like: 价格格式
facebook_app_settings: 的Facebook应用程序设置
enable_facebook_login: 启用Facebook登录
fb_app_id: Facebook应用程序ID
fb_secret_key: Facebook的秘密密钥
comment_settings: 注释设置
enable_comment: 启用评论
disqus_shortname: Disqus SHORTNAME
sandbox_mode: 沙盒模式
item_name: 项目名称
paypal_email: 的PayPal电子邮件
currency: 货币
finish_url: 完成网址
cancel_url: 取消URL
menu_background: 菜单背景
menu_text_color: 菜单文本颜色
activated_menu_color: 激活菜单颜色
top_bar_bg: 顶部栏BG
activated_menu_text_color: 激活菜单文本颜色
latitude: 纬度
longitude: 经度
map_zoom: 地图缩放
search_panel_settings: 搜索面板设置
search_panel_bg_color: 搜索面板背景色的
show_background_image: 显示背景图片
active_widget_position: 活动部件位置
upload_and_install: 上传和安装
install_updates: 安装更新/主题/插件/小工具
confirmation_email: 确认电子邮件
recovery_email: 恢复电子邮件
signup_notification_email: 注册通知电子邮件
payment_confirmation_email: 付款确认电子邮件
click_and_edit: 选择一个模板文件，然后单击编辑]
google_analytics_settings: 谷歌AnalyticsSettings
default_seo_settings: 默认SEO设置
find_us_on_facebook: Facebook上找到我们
category_featured_posts: 精选文章
load_more_posts: 加载更多
home_page_title: 搜索买东西卖汽车
no_posts_found: 没有帖子
type_anything: 键入任何
chosen_not_found: 哎呀，没有找到！
rating_asc: 评分升序
rating_desc: 评分降序
id_desc: 编号降序
id_asc: 编号升序
price_range: 价格范围
additional_features: 的附加功能
add_more_fields: 添加更多的字段
remove: 删除
distance_around_my_position: 搜索半径
show_distance_in: 在显示距离
car_listed: 汽车发布
show_street_view: 显示街景
list_car: 列表汽车
search_cars: 搜索汽车
top_cars: 顶级汽车
featured_cars: 精选汽车
content_settings: 内容设置
hide_email: 隐藏电子邮件
hide_phone: 隐藏手机
review: 回顾
comment: 评论
submit_review: 提交评论
rating: 评级
review_alert: 您必须登录到提交审查。
new_car: 新增汽车
identify_my_location: 识别我的位置
data_deleted: 数据删除
recent_reviews: 最近评论
view_all_reviews: 浏览全部评论
review_deleted: 已删除评论
review_detail: 详细
all_reviews: 所有评论
monday: 周一
tuesday: 周二
wednesday: 周三
thursday: 周四
friday: 周五
saturday: 周六
sunday: 周日
opening_hour: 开放时间
closed: 休息
review_submitted: 送审
social_links: 社会链接
upgrade_browser: 升级浏览器
please_upgrade_your_browser: ，请升级浏览器
car: 汽车
introduction: 介绍
terms: 条款和条件
email_not_found: 电子邮件没有找到
city_dropdown: 城市下拉
published: 发布
publish: 发布
drafted: 起草
draft: 草案
from: 从
send_bulk_email: 发送大量电子邮件
ive_read_the: 我看了
title_city_category: 标题，城市或类别
dt_first: 首页
dt_last: 最后
dt_next: 下一页
dt_prev: 上一页
dt_no_data: 无表可用的数据
dt_show_empty: 显示0到0的条目
dt_no_match: 不匹配的记录中发现
dt_search: 的搜索
dt_processing: 处理...
dt_loading: 载入中...
dt_info: 显示_START_到_TOTAL_项_END_
dt_filter_info: （从_MAX_总过滤项）
dt_show_entries: 显示_MENU_项
get_directions: 获得方向
review_not_submitted : 你已经给了审查
debug_email : 调试电子邮件
email_to : Email给
report_the_car : 举报此车
reported : 报
already_reported : 已报道的
reported_post : 报道汽车
all_reported_posts : 报道汽车
report: 报告
assigned_to: 分配到
select_assigned_to: 选择用户
css_compression: 的CSS压缩
gallery_notes: 你可以拖放重新排列相册。照片不重新调整大小。
video_notes: YouTube或Vimeo的网址
post_expiration_notification: 后到期通知
days_left: 剩余天
AM: AM
PM: PM
upload_invalid_min_dimensions: 的图像尺寸是过低
view_on_front: 的前视图
clear_unused_img: 清除未使用的图片
unused_files_found: 未使用的文件中发现
unused_images_cleared: 未使用的图片清除
unused_info_msg: 此功能仅清除未使用的汽车，用户，类别，网页，博客的图像。它通过搜索数据库寻找images.So如果手动手动上传任何图片，并可以删除代码中使用它们。
no_unused_img: 未使用的图像发现
search_panel_filter_type: 过滤器型
basic_options: 基本选择
advanced_options: 高级选项
sorting_order: 排序顺序
car_listed_on: 汽车上列出
car_listed_under: 下面列出汽车
all_sub_categories: 所有子类
no_sub_categories: 无子类别
hide_my_email : 隐藏我的电子邮件
disable_email_contact: 禁用邮件联系人
enable_review: 启用审查
disable_google_street_view: 禁用谷歌街景
location_chorome_msg: 的谷歌位置服务不适用于非SSL站点（仅适用于Chrome浏览器）。你想用你的IP地址，让你的位置？NB-结果可能不完全一样谷歌
send_email_to_users: 向用户发送电子邮件
show_banner: 展示横幅广告
hide_my_phone: 隐藏我的电话
kms: 公里
miles: 数
logo_text: 标志文本
logo_type: 标志类型
logo_text_color: 标志文本颜色
Jan: 一月
Feb: 二月
Mar: 三月
Apr: 四月
May: 五月
Jun: 六月
Jul: 七月
Aug: 八月
Sep: 九月
Oct: 十月
Nov: 十一月
Dec: 十二月
show_search_panel: 显示搜索面板
delete_selected: 删除所选
map_api_key: GMAP API密钥
pricing: 定价
post_package_instruction: 我们有以下的包我们的网站上张贴的车
feature_package_instruction: 我们有用于制造汽车功能的下列包
MENU: MENU
gplus_app_settings: Google+应用设置
auth_redirect_url: 授权重定向URL
enable_gplus_login: 启用Google+登录
gplus_client_id: Google+的客户端ID
gplus_client_secret: 的Google+客户端密钥
how_to_get_gplus_api: 如何获取Google+客户端ID和密钥
gallery_upload_limit: 库上传限制
you_can_upload_max: 你可以上传最大
gallery_photos: 相册
advanced_options_with_country_state: 与国家和国家高级选项
select_state: 中选择状态
recent_posts_order: 最近的帖子订购
featured_posts_order: 精选文章责令
default_posts_order: 默认文章顺序
ASC: 升序
DESC: 降序
RANDOM: 随机
useremail: 用户电子邮件
enable_adblocker_alert: 启用Adblock的警报
adblock_detected: Adblock的检测
adblock_msg: ，请确定停用的AdBlock，并再次刷新页面
enable_cookie_policy_popup: Cookie政策弹出
cookie_policy_page_url: 的Cookie政策网页的网址
cookie_policy: Cookie政策
cookie_policy_alert: 本网站使用cookies。继续使用这个网站，你同意我们使用Cookie。
read_more: 了解更多
i_agree: 我同意
instagram: 的Instagram
newsletter_subscription: 获取通讯
your_email: 您的邮箱
email_saved: 的电子邮件保存的新闻邮件
send_newsletter: 发送时事通讯
unsubscribe: 退订
to_unsubscribe: ，如果你想从这项服务中取消订阅点击此链接
successfully_unsubscribed: 你现在从通讯服务退订
export_user_phone: 导出用户电话
enable_blog_comment: 启用博客评论
fb_blog_app_id: 的博客FB应用程序ID
disqus_blog_shortname: Disqus短名称博客
sample_page: 示例页面
senders_phone: 发送者的电话
alias: 别名
atleast_a_country_city: 您必须至少输入国家和城市
email_not_shared: 看来，Facebook的帐号不具有共享电子邮件的权限。请更改或用户其他帐户或只是立即登记使用电子邮件。
votes: 投票
food_corner: 食品角落
show_map_instead_of_street_view: 显示地图，而不是街头查看
post_published_email: 帖子发表电子邮件
max_upload_file_size: 最大上传大小（KB）
site_mode: 站点模式
maintenance_msg: 网站正在维护
brandmodels: 品牌型号
add_brand: 添加品牌
add_model: 添加的模型
no_brandmodels: 没有brandmodels
sel_brand: 选择品牌
carconditions: 汽车的条件
STATUS_DELETED: 已删除的
STATUS_ACTIVE: 活动
STATUS_PENDING: 待定
STATUS_PAYMENT_PENDING: 付款等待
STATUS_EXPIRED: 过期
USER_PENDING: 发送暂缓
USER_BANNED: 禁止的
USER_ACTIVE: 活动
car_options: 车的配置选项
transmissions: 变速箱类型
convertible: 转换
coupe: 跑车
hatchback: 两厢
luxury_car: 豪华轿车
sedan: 轿车
sports_car: 跑车
suv: SUV
trucks: 卡车
van: 范
customfields: 的自定义字段
customfield: 自定义字段
sel_fieldtype: 选择字段类型
text: 文本
textarea: 文本区
richtext: 富文本格式
select: 下拉
radio: 无线电
checkbox: 复选框
is_required: 是否需要
field_added: 自定义字段添加
field_updated: 自定义字段更新的
field_deleted: 自定义字段删除
field_order_updated: 字段顺序更新。
field_sort_help: ^你可以拖放到表行进行排序。排序保存订单之后
help_url_slug: 把一个唯一的值（将在URL中使用）
NA: N / A
condition_new: 新的
condition_used: 用于
condition_pre_owned: 预国有
condition_recondition: 翻新
condition_other: 其他
year: 体型
brand: 汽车品牌
model: 汽车模型
mileage: 里程
transmission: 传输
condition: 条件
fuel_type: 燃料类型
fueltypes: 燃料类型
gas: 燃气
diesel: DISEL
petrol: 汽油
octane: 辛烷值
electricity: 电力
others: 其他
select_condition: 选择条件
select_transmission: 选择变速箱
automatic: 自动
manual: 手动
semi_automatic: 半自动
select_brand: 选择品牌
select_year: 选择体型
select_fuel_type: 选择燃料类型
url_slug: 网址弹头
registration_no: 注册号
engine_size: 发动机尺寸
help_engine_size: 发动机的体积（升）
steering_type: 转向型式
help_steering_type: 选择转向型式
safety_rating: 安全等级
sel_safety_rating: 选择安全等级
engine_type: 发动机型号
help_engine_type: 选择发动机型号
no_of_seats: 没有座位的
help_no_of_seats: 座位的无
gear_type: 齿轮类型
help_gear_type: 选择齿轮式
new_brand: 新品牌
brand_names: 品牌名称
new_model: 新型号
select_model: 选择型号
model_names: 型号名称
mileage_unit: 里程单位
brand_model: 品牌及型号
help_text: 的帮助文本
fieldtype: 字段类型
fieldname: 字段名称
comma_separated_help: 将一个或多个命名为“”（逗号）分隔。像纽约，达拉斯，爱达荷州
category_id: 轿车品类
show_in_detail: 中的详细信息页面显示
power_steering: 动力转向
manual_steering: 手动转向
inline: 在线
straight: 直
vee: VEE
flat: 平
vr_w: VR＆W
other: 其他
other_information: 其他信息
dual: 双
all_cars: 所有汽车
reported_cars: 报道汽车
no_reviews: 暂时还没有评论
optional_info: 可选信息
car_posts: 租车帖子
featured_expiration_time: 精选到期时间（天）
max_gallery_photos: 最大相册
gallery_limit: 图库
take_package: 拿包
photos: 照片
mileage_range: 的续航里程
pls_share: 请分享我们的网站
facebook_page_name: FB页面名称
google_plus_name: 的Google+名称
twitter_page_name: Twitter的用户名
normal: 普通
free: 免费
ultimate: 终极
premium: 高级
update_post: 更新后
Clear unused images: 清除未使用的图像